#!/usr/bin/env sh

# Runs a code scan, sends the results to Sonarqube, and checks if the quality gate passed

echo "Publishing scan results"
$TOOLS_PATH/sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner \
    -Dsonar.host.url=$SONAR_URL \
    -Dsonar.login=$SONAR_LOGIN \
    -Dsonar.gitlab.project_id=$CI_PROJECT_PATH \
    -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
    -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
    -Dsonar.gitlab.failure_notification_mode=exit-code \
    $@  # Add any additional params


echo "Checking quality gate"
# Break build if quality gate did not succeed
java -jar $TOOLS_PATH/sonar-gate-breaker-all-1.0.1.jar -u $SONAR_LOGIN -t .scannerwork/report-task.txt
