#!/usr/bin/env sh

# Runs a code scan, and publishes inline comments with the issues found

echo "Scanning for issues"
$TOOLS_PATH/sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner \
    -Dsonar.host.url=$SONAR_URL \
    -Dsonar.login=$SONAR_LOGIN \
    -Dsonar.gitlab.project_id=$CI_PROJECT_PATH \
    -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
    -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
    -Dsonar.gitlab.failure_notification_mode=exit-code \
    -Dsonar.analysis.mode=preview \
    $@  # Add any additional params
